config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "users/registrations"}
  resources :users
  root 'static_pages#top'

  get 'static_pages/about', as: 'about'

  get 'static_pages/terms', as: 'terms'

  get 'static_pages/privacy', as: 'privacy'

  #ポストページのルート設定
  resources :posts, only: [:show, :new, :edit, :create, :update, :destroy]

  #Blogのルート設定
  resources :blogs

  #Chatのルート設定
  resources :chat_rooms, only: [:new, :create, :show, :index, :destroy]
  mount ActionCable.server => '/cable'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  default_scope -> { order(created_at: :desc)}
  validates :title, presence: true, length: { maximum: 20}
  validates :text, presence: true, length: { maximum:300}

  mount_uploaders :blogpicture, BlogPictureUploader
  serialize :blogpicture, JSON #carrierwave マルチアップロードの設定
  #validates :blogpicture, presence: true #seedを入れるときはオフにする!!
  validate :check_blogpictures #Blogにアップロードできる写真の枚数制限


   def check_blogpictures #Blogにアップロードできる写真の枚数制限
      if blogpicture.size > 2
       errors.add(:blogpicture,"は2枚迄です。")
      end
   end


end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
 before_action :authenticate_user!, only: [:new, :create, :index, :edit, :update, :destroy]
 before_action :correct_blog_owner, only: [:edit, :update, :destroy]
 before_action :set_blog, only: [:show, :edit, :update, :destroy]

 respond_to :json

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new(blog_params)

    if @blog.save
    notice
    redirect_to @blog, notice: "ブログが作成.保存されました。"
    else
    render 'new', notice: "ブログが作成.保存されませんでした。"
    end
  end

  def show

  end

  def index
    @blogs = @current_user.blogs.order(created_at: :desc).paginate(page: params[:page], per_page: 3)
  end

  def edit

  end

  def update

    if @blog.update(blog_params)
      redirect_to @blog
      flash[:notice] = "ブログが更新されました。"
    else
      render 'edit'
    end
  end

  def destroy
    
    @blog.destroy
    redirect_to blogs_path
    flash[:notice] = "ブログが削除されました。"
  end

  private

  def set_blog
    @blog = Blog.find(params[:id])
  end

  def correct_blog_owner
    @blog = Blog.find_by(id: params[:id])
    if @blog.user_id != @current_user.id
     flash[:notice] = "この記事のアクセス権限が有りません"
     redirect_to root_url
    end
  end

  def blog_params
  params.require(:blog).permit(:title, :text, {blogpicture: []}, :user_id)
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_form.html.erb
<%= form_for(blog) do |f| %>

  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<p>
  <%= f.label :title %>
  <%= f.text_field :title %>
</p>

<p>
  <%= f.label :picture %>
  <%= f.file_field :blogpicture, accept: 'image/jpeg,image/gif,image/png', :multiple => true %>
  <%#= image_tag blog.blogpicture.url if blog.blogpicture.present? %>
  <%= f.hidden_field :blogpicture_cache %>
</p>

<p>
   <%= f.label :text %>
   <%= f.text_area :text %>
</p>

  <%= f.hidden_field :user_id, value: current_user.id %>

<p>
  <%= f.submit %>
</P>
 <% end %>

 <script type="text/javascript">
  $('#blog_blogpicture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 2) {
      alert('ファイルサイズを小さくして下さい。ファイルサイズは2MB迄です。');
    }
  });
</script>

app/views/blogs/edit.html.erb
<% provide(:title, "Blog Edit") %>
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %><!--Formのパーシャル-->
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<% provide(:title, "Blog Index") %>
<h1>Blogのindexページです</h1>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>

   <%= link_to 'New blog', new_blog_path %>

  <% @blogs.each do |blog| %>
  <tr>
  <td><%= blog.title %></td>
  <td><%= blog.text %></td>
  <td><%= image_tag(blog.blogpicture[0].url, size: "40x40") if blog.blogpicture? %> <!--arrayファイルの選択[0]公式ページを参照-->
  <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
  <td><%= link_to 'Destroy', blog_path(blog), method: :delete, data: { confirm: '本当に削除しますか？'}%></td>
  <td><a href="<%= blog_path(blog.id) %>"> Read more </a></td>
  </tr>
  <% end %>

</table>

<%= will_paginate @blog_page %>

app/views/blogs/new.html.erb
<% provide(:title, "New Blog") %>
<h1>New Blogページです。</h1>

<%= render 'form', blog: @blog %><!--Formのパーシャル-->
<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<% provide(:title, "Blog Show") %>
<h1>BlogのShowページです</h1>

<p>
  <strong>Title</strong>
  <%= @blog.title %>
</p>

<p>
  <!--<strong>Picture</strong>-->
  <% if @blog.blogpicture? %>
       <% @blog.blogpicture.each do |picture| %>
       <%= image_tag(picture.url, size: "200x200") %>
       <% end %>
  <% end %>
</p>

<p>
  <strong>Text</strong>
  <%= simple_format(text_url_to_link(h(@blog.text)).html_safe) %> <!--simple_formatでBlog textの改行 && アプリケーションヘルパーのtext_url_to_linkでtextのリンクを有効にしてる -->
</p>


<% if user_signed_in? && current_user.id == @blog.user_id %>
<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>
<% end %>