config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "users/registrations"}
  resources :users
  root 'static_pages#top'

  get 'static_pages/about', as: 'about'

  get 'static_pages/terms', as: 'terms'

  get 'static_pages/privacy', as: 'privacy'

  #ポストページのルート設定
  resources :posts, only: [:show, :new, :edit, :create, :update, :destroy]

  #Blogのルート設定
  resources :blogs

  #Chatのルート設定
  resources :chat_rooms, only: [:new, :create, :show, :index, :destroy]
  mount ActionCable.server => '/cable'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "About", about_path %> </li>
      <li><%= link_to "Privacy Policy", privacy_path %> </li>
      <li> <%= link_to "Terms", terms_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-default">
  <div class="container">
    <%= link_to "48", root_path, id: "logo" %> <!--サイトロゴ-->
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", '#' %></li>

        <% if user_signed_in? %>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <li class="round-image"><%= image_tag(current_user.avatar.url(:thumb)) %><li><!--プロフ写真-->
            <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "プロフィール", current_user %></li>
              <% if current_user.post.present? %>
              <li><%= link_to "My Post", current_user.post %></li> <%# 新規投稿と既に投稿した場合でリンクを切り替える(投稿済みの場合のリンク)%>
              <% else %>
              <li><%= link_to "新規投稿", new_post_path %></li><%# 新規投稿と既に投稿した場合でリンクを切り替える(新規の場合のリンク)%>
              <% end %>
              <li><%= link_to "Blog", blogs_path %></li>
              <li><%= link_to "チャット",chat_rooms_path %></li>
              <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
          <% else %>
              <li><%= link_to "ログイン", new_user_session_path %></li>
              <li><%= link_to "新規登録", new_user_registration_path %></li>
          <% end %>
            </ul>
          </li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title))%></title> <%#ページのタイトル表示 appliication helper参照%>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
        <%= render 'layouts/header' %>
    <div class="container">
    <%= yield %>
    <%= render 'layouts/footer' %>
    </div>

    <!--Flashにメッセージがある時-->
    <% unless flash.empty? %>
       <script type="text/javascript" >
         <% flash.each do |f| %>
          <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
          toastr['<%= type %>']('<%= f[1] %>');
         <% end %>
       </script>
    <% end %>

    <%= debug(params) if Rails.env.development? %> <%#developmentの場合のみデバッグ情報を表示する%>
  </body>
</html>